const propertiesOrder = [
  'all', // all: initial should be first

  'position',
  'z-index',
  'top',
  'right',
  'left',
  'bottom',

  'margin',
  'margin-x',
  'margin-y',
  'margin-top',
  'margin-right',
  'margin-bottom',
  'margin-left',
  'padding',
  'padding-x',
  'padding-y',
  'padding-top',
  'padding-right',
  'padding-left',
  'padding-bottom',

  'display',
  'visibility',
  'float',
  'clear',
  'overflow',
  'overflow-x',
  'overflow-y',
  'clip',
  'zoom',
  'flex-direction',
  'flex-order',
  'flex-pack',
  'flex-align',

  'box-sizing',
  'width',
  'min-width',
  'max-width',
  'height',
  'min-height',
  'max-height',

  'table-layout',
  'empty-cells',
  'caption-side',
  'border-spacing',
  'border-collapse',
  'list-style',
  'list-style-position',
  'list-style-type',
  'list-style-image',

  'font',
  'font-family',
  'font-size',
  'font-weight',
  'font-style',
  'font-variant',
  'font-size-adjust',
  'font-stretch',
  'font-effect',
  'font-emphasize',
  'font-emphasize-position',
  'font-emphasize-style',
  'font-smooth',
  'line-height',
  'text-align',
  'text-align-last',
  'vertical-align',
  'white-space',
  'text-decoration',
  'text-emphasis',
  'text-emphasis-color',
  'text-emphasis-style',
  'text-emphasis-position',
  'text-indent',
  'text-justify',
  'letter-spacing',
  'word-spacing',
  'text-outline',
  'text-transform',
  'text-wrap',
  'text-overflow',
  'text-overflow-ellipsis',
  'text-overflow-mode',
  'text-shadow',
  'word-wrap',
  'word-break',
  'tab-size',
  'hyphens',

  'cursor',
  'user-select',
  'pointer-events',

  'content',
  'quotes',
  'counter-reset',
  'counter-increment',
  'resize',

  'nav-index',
  'nav-up',
  'nav-right',
  'nav-down',
  'nav-left',

  'color',
  'background',
  'background-color',
  'background-image',
  'background-repeat',
  'background-attachment',
  'background-position',
  'background-position-x',
  'background-position-y',
  'background-clip',
  'background-origin',
  'background-size',
  'border',
  'border-width',
  'border-style',
  'border-color',
  'border-top',
  'border-top-width',
  'border-top-style',
  'border-top-color',
  'border-left',
  'border-left-width',
  'border-left-style',
  'border-left-color',
  'border-right',
  'border-right-width',
  'border-right-style',
  'border-right-color',
  'border-bottom',
  'border-bottom-width',
  'border-bottom-style',
  'border-bottom-color',
  'border-radius',
  'border-top-left-radius',
  'border-top-right-radius',
  'border-bottom-right-radius',
  'border-bottom-left-radius',
  'border-image',
  'border-image-source',
  'border-image-slice',
  'border-image-width',
  'border-image-outset',
  'border-image-repeat',
  'outline',
  'outline-width',
  'outline-style',
  'outline-color',
  'outline-offset',
  'opacity',
  'box-shadow',
  'box-decoration-break',

  'transition',
  'transition-duration',
  'transition-delay',
  'transition-timing-function',
  'transition-property',
  'transform',
  'transform-origin',
  'animation',
  'animation-name',
  'animation-duration',
  'animation-play-state',
  'animation-timing-function',
  'animation-delay',
  'animation-iteration-count',
  'animation-direction',
  'backface-visibility',
  'will-change',
]


module.exports = {
  extends: 'stylelint-config-standard',
  rules: {
    // disable for sugarss
    'declaration-block-trailing-semicolon': null,
    'block-opening-brace-space-before': null,

    // what quotes must be used
    'font-family-name-quotes': 'always-where-recommended',
    'function-url-quotes': 'always',
    'string-quotes': 'single',

    // the order of properties
    'declaration-block-properties-order': propertiesOrder,

    // disable prefixes
    'at-rule-no-vendor-prefix': true,
    'media-feature-name-no-vendor-prefix': true,
    'property-no-vendor-prefix': true,
    'selector-no-vendor-prefix': true,
    'value-no-vendor-prefix': true,

    // control specificity
    'max-nesting-depth': 3,
    'selector-max-compound-selectors': 3,
    'selector-max-specificity': '0,3,0',

    // acceptable selector types, units, properties, functions and words in comments

    'color-named': 'always-where-possible',
    'comment-word-blacklist': ['TODO', 'FIXME'],
    'declaration-no-important': true,
    'selector-no-qualifying-type': true,
    'selector-no-type': true,
    'selector-no-universal': true,

    // a notation when there are one or more valid representations
    'font-weight-notation': 'named-where-possible',

    // the acceptable use of custom properties
    'custom-property-no-outside-root': true,
    'selector-root-no-composition': true,

    // if Data URIs must or must not be used
    // use webpack
    'function-url-data-uris': 'never',

    // a maximum line length
    'max-line-length': 120,
  },
}
